apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: staging-prod-deploy
profiles:
  - name: staging
    deploy:
      kubeContext: gke_tech-rnd-project_us-central1-a_skaffold-cluster
      kubectl:
        manifests:
          - template-master/k8/deployment.yaml
          - template-master/k8/service.yaml
